language: ruby

rvm:
  - 2.0.0
  - 2.1
  - 2.2.0

sudo: false

cache: bundler

before_install:
  - npm i -g bower

before_script:
  - mysql -e 'create database foodbase_test;'
  - bower install
  - bundle exec rake db:migrate

bundler_args: --without development --deployment --retry=3 --jobs=3

script: 'bundle exec rspec'

notifications:
  email: false
